# -*- coding: utf-8 -*-
"""preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r0jSMBsBzhK0_NT5Yn8HyLT3IHmliAuN
"""

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer



def build_preprocessor(numeric_features, categorical_features):

    """
    Builds preprocessing pipeline for numeric and categorical features
    """
    numeric_pipeline = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),   # handle missing numeric values
        ("scaler", StandardScaler())                     # scale numeric features
    ])

    categorical_pipeline = Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),  # fill missing categories
        ("encoder", OneHotEncoder(handle_unknown="ignore"))    # convert categories to numbers
    ])

    column_transformer = ColumnTransformer(
        transformers=[
            ("num", numeric_pipeline, numeric_features),
            ("cat", categorical_pipeline, categorical_features)
        ]
    )

    return column_transformer